-- Inserindo dados na tabela ARTISTA
INSERT INTO ARTISTA (ID_ARTISTA, NOME) VALUES (SEQ_ARTISTA.NEXTVAL,
'AnaVitória');
INSERT INTO ARTISTA (ID_ARTISTA, NOME) VALUES (SEQ_ARTISTA.NEXTVAL,
'Lagum');
INSERT INTO ARTISTA (ID_ARTISTA, NOME) VALUES (SEQ_ARTISTA.NEXTVAL,
'Imagine Dragons');
INSERT INTO ARTISTA (ID_ARTISTA, NOME) VALUES (SEQ_ARTISTA.NEXTVAL,
'Coldplay');
-- Inserindo dados na tabela ALBUM
INSERT INTO ALBUM (ID_ALBUM, NOME, ANO_LANCAMENTO, ID_ARTISTA) VALUES
(SEQ_ALBUM.NEXTVAL, 'Cor', 2022, 1);
-- AnaVitória
INSERT INTO ALBUM (ID_ALBUM, NOME, ANO_LANCAMENTO, ID_ARTISTA)
VALUES (SEQ_ALBUM.NEXTVAL, 'Memórias (De onde eu nunca fui)', 2023, 2);
-- Lagum
INSERT INTO ALBUM (ID_ALBUM, NOME, ANO_LANCAMENTO, ID_ARTISTA)
VALUES (SEQ_ALBUM.NEXTVAL, 'Mercury - Act 1', 2021, 3);
-- Imagine Dragons
INSERT INTO ALBUM (ID_ALBUM, NOME, ANO_LANCAMENTO, ID_ARTISTA)
VALUES (SEQ_ALBUM.NEXTVAL, 'Music of the Spheres', 2021, 4);
-- Coldplay
-- Inserindo dados na tabela MUSICA
INSERT INTO MUSICA (ID_MUSICA, TITULO, DURACAO, ANO_LANCAMENTO, ID_ALBUM)
VALUES (SEQ_MUSICA.NEXTVAL, 'Amarelo, Azul e Branco', 234, 2022, 1);
-- AnaVitória
INSERT INTO MUSICA (ID_MUSICA, TITULO, DURACAO, ANO_LANCAMENTO, ID_ALBUM)
VALUES (SEQ_MUSICA.NEXTVAL, 'universo de coisas que eu desconheço', 187,
2022, 1);
-- AnaVitória
INSERT INTO MUSICA (ID_MUSICA, TITULO, DURACAO, ANO_LANCAMENTO, ID_ALBUM)
VALUES (SEQ_MUSICA.NEXTVAL, 'Deixa', 256, 2023, 2);
-- Lagum
INSERT INTO MUSICA (ID_MUSICA, TITULO, DURACAO, ANO_LANCAMENTO, ID_ALBUM)
VALUES (SEQ_MUSICA.NEXTVAL, 'Enemy', 173, 2021, 3);
-- Imagine Dragons
INSERT INTO MUSICA (ID_MUSICA, TITULO, DURACAO, ANO_LANCAMENTO, ID_ALBUM)
VALUES (SEQ_MUSICA.NEXTVAL, 'My Universe', 228, 2021, 4);
-- Coldplay
-- Inserindo dados na tabela GENERO_MUSICAL
INSERT INTO GENERO_MUSICAL (ID_GENERO, NOME) VALUES (SEQ_GENERO.NEXTVAL,
'MPB');
INSERT INTO GENERO_MUSICAL (ID_GENERO, NOME) VALUES (SEQ_GENERO.NEXTVAL,
'Pop');
INSERT INTO GENERO_MUSICAL (ID_GENERO, NOME) VALUES (SEQ_GENERO.NEXTVAL,
'Rock Alternativo');
INSERT INTO GENERO_MUSICAL (ID_GENERO, NOME) VALUES (SEQ_GENERO.NEXTVAL,
'Indie');
-- Inserindo dados na tabela MusicaGenero
INSERT INTO MusicaGenero (ID_MUSICA, ID_GENERO) VALUES (1, 1);
-- Amarelo, Azul e Branco - MPB
INSERT INTO MusicaGenero (ID_MUSICA, ID_GENERO) VALUES (1, 2);
-- Amarelo, Azul e Branco - Pop
INSERT INTO MusicaGenero (ID_MUSICA, ID_GENERO) VALUES (2, 1);
-- universo de coisas que eu desconheço - MPB
INSERT INTO MusicaGenero (ID_MUSICA, ID_GENERO) VALUES (3, 3);
-- Deixa - Rock Alternativo
INSERT INTO MusicaGenero (ID_MUSICA, ID_GENERO) VALUES (4, 3);
-- Enemy - Rock Alternativo
INSERT INTO MusicaGenero (ID_MUSICA, ID_GENERO) VALUES (5, 2);
-- My Universe - Pop
-- Inserindo dados na tabela USUARIO
INSERT INTO USUARIO (ID_USUARIO, NOME, EMAIL, DATA_NASCIMENTO)
VALUES (SEQ_USUARIO.NEXTVAL, 'João Silva', 'joao.silva@email.com',
TO_DATE('1990-05-10', 'YYYY-MM-DD'));
INSERT INTO USUARIO (ID_USUARIO, NOME, EMAIL, DATA_NASCIMENTO)
VALUES (SEQ_USUARIO.NEXTVAL, 'Maria Oliveira', 'maria.oliveira@email.com',
TO_DATE('1985-12-22', 'YYYY-MM-DD'));
-- Inserindo dados na tabela PLAYLIST
INSERT INTO PLAYLIST (ID_PLAYLIST, NOME, DESCRICAO, ID_USUARIO)
VALUES (SEQ_PLAYLIST.NEXTVAL, 'MPB Favoritas', 'Minhas músicas favoritas
de MPB', 1);
INSERT INTO PLAYLIST (ID_PLAYLIST, NOME, DESCRICAO, ID_USUARIO)
VALUES (SEQ_PLAYLIST.NEXTVAL, 'Rock Internacional', 'Músicas de rock
internacional que eu gosto', 2);
INSERT INTO PlaylistMusica (ID_PLAYLIST, ID_MUSICA, ORDEM) VALUES (1, 1,
1);
-- MPB Favoritas - Amarelo, Azul e Branco
INSERT INTO PlaylistMusica (ID_PLAYLIST, ID_MUSICA, ORDEM) VALUES (1, 2,
2);
-- MPB Favoritas - universo de coisas que eu desconheço
INSERT INTO PlaylistMusica (ID_PLAYLIST, ID_MUSICA, ORDEM) VALUES (2, 4,
1);
-- Rock Internacional - Enemy
INSERT INTO PlaylistMusica (ID_PLAYLIST, ID_MUSICA, ORDEM) VALUES (2, 5,
2);
-- Rock Internacional - My Universe